version: '3'

services:
  edevo-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edevo-web
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - edevo-network

networks:
  edevo-network:
    name: edevo-network
    driver: bridge
